import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "./Components/Navbarwrape";
import BottomNavbar from "./Components/BottomNavbar";
import AppHeightWrapper from "./AppHeightWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-full antialiased`}
      >
        <NavbarWrapper />
        <AppHeightWrapper> {children}</AppHeightWrapper>
        <BottomNavbar />
      </body>
    </html>
  );
}
